=== JochenLinnemann/netShore-TCG/src/de/netshore/tcg/services.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!--
           Copyright 2005, 2017 Jochen Linnemann

           Licensed under the Apache License, Version 2.0 (the "License");
           you may not use this file except in compliance with the License.
           You may obtain a copy of the License at

               http://www.apache.org/licenses/LICENSE-2.0

           Unless required by applicable law or agreed to in writing, software
           distributed under the License is distributed on an "AS IS" BASIS,
           WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
           See the License for the specific language governing permissions and
           limitations under the License.
        -->
        <!ELEMENT services (service+)>

        <!ELEMENT service (enlistment,survival,commission,promotion,reenlistment,ranks,mustering-out,skills)>
        <!ATTLIST service
                name CDATA #REQUIRED
                draft (0|1|2|3|4|5|6) #REQUIRED
                >

        <!ELEMENT enlistment (str|dex|end|int|edu|soc)*>
        <!ATTLIST enlistment min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #REQUIRED>

        <!ELEMENT survival (str|dex|end|int|edu|soc)?>
        <!ATTLIST survival min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #REQUIRED>

        <!ELEMENT commission (str|dex|end|int|edu|soc)?>
        <!ATTLIST commission min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #IMPLIED>

        <!ELEMENT promotion (str|dex|end|int|edu|soc)?>
        <!ATTLIST promotion min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #IMPLIED>

        <!ELEMENT reenlistment EMPTY>
        <!ATTLIST reenlistment min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #REQUIRED>

        <!ELEMENT ranks (r1?,r2?,r3?,r4?,r5?,r6?)>
        <!ATTLIST ranks
                without CDATA #REQUIRED
                prefix CDATA #REQUIRED
                >
        <!ELEMENT r1 EMPTY>
        <!ATTLIST r1 name CDATA #REQUIRED>
        <!ELEMENT r2 EMPTY>
        <!ATTLIST r2 name CDATA #REQUIRED>
        <!ELEMENT r3 EMPTY>
        <!ATTLIST r3 name CDATA #REQUIRED>
        <!ELEMENT r4 EMPTY>
        <!ATTLIST r4 name CDATA #REQUIRED>
        <!ELEMENT r5 EMPTY>
        <!ATTLIST r5 name CDATA #REQUIRED>
        <!ELEMENT r6 EMPTY>
        <!ATTLIST r6 name CDATA #REQUIRED>

        <!ELEMENT mustering-out (benefits,cash)>

        <!ELEMENT benefits (b1,b2,b3,b4,b5,b6?,b7?)>
        <!ELEMENT b1 EMPTY>
        <!ATTLIST b1 name CDATA #REQUIRED>
        <!ELEMENT b2 EMPTY>
        <!ATTLIST b2 name CDATA #REQUIRED>
        <!ELEMENT b3 EMPTY>
        <!ATTLIST b3 name CDATA #REQUIRED>
        <!ELEMENT b4 EMPTY>
        <!ATTLIST b4 name CDATA #REQUIRED>
        <!ELEMENT b5 EMPTY>
        <!ATTLIST b5 name CDATA #REQUIRED>
        <!ELEMENT b6 EMPTY>
        <!ATTLIST b6 name CDATA #REQUIRED>
        <!ELEMENT b7 EMPTY>
        <!ATTLIST b7 name CDATA #REQUIRED>

        <!ELEMENT cash (c1,c2,c3,c4,c5,c6,c7)>
        <!ELEMENT c1 EMPTY>
        <!ATTLIST c1 name CDATA #REQUIRED>
        <!ELEMENT c2 EMPTY>
        <!ATTLIST c2 name CDATA #REQUIRED>
        <!ELEMENT c3 EMPTY>
        <!ATTLIST c3 name CDATA #REQUIRED>
        <!ELEMENT c4 EMPTY>
        <!ATTLIST c4 name CDATA #REQUIRED>
        <!ELEMENT c5 EMPTY>
        <!ATTLIST c5 name CDATA #REQUIRED>
        <!ELEMENT c6 EMPTY>
        <!ATTLIST c6 name CDATA #REQUIRED>
        <!ELEMENT c7 EMPTY>
        <!ATTLIST c7 name CDATA #REQUIRED>

        <!ELEMENT skills (automatic-skills,personal-development,service-skills,advanced-education,advanced-education-edu8plus)>
        <!ATTLIST skills eligibility (1|2) #REQUIRED>

        <!ELEMENT automatic-skills (r0?,r1?,r2?,r3?,r4?,r5?,r6?)>
        <!ELEMENT r0 EMPTY>
        <!ATTLIST r0 name CDATA #REQUIRED>

        <!ELEMENT personal-development (s1,s2,s3,s4,s5,s6)>
        <!ELEMENT service-skills (s1,s2,s3,s4,s5,s6)>
        <!ELEMENT advanced-education (s1,s2,s3,s4,s5,s6)>
        <!ELEMENT advanced-education-edu8plus (s1,s2,s3,s4,s5,s6)>
        <!ELEMENT s1 EMPTY>
        <!ATTLIST s1 name CDATA #REQUIRED>
        <!ELEMENT s2 EMPTY>
        <!ATTLIST s2 name CDATA #REQUIRED>
        <!ELEMENT s3 EMPTY>
        <!ATTLIST s3 name CDATA #REQUIRED>
        <!ELEMENT s4 EMPTY>
        <!ATTLIST s4 name CDATA #REQUIRED>
        <!ELEMENT s5 EMPTY>
        <!ATTLIST s5 name CDATA #REQUIRED>
        <!ELEMENT s6 EMPTY>
        <!ATTLIST s6 name CDATA #REQUIRED>

        <!ELEMENT str EMPTY>
        <!ATTLIST str
                min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #REQUIRED
                dm (1|2) #REQUIRED
                >
        <!ELEMENT dex EMPTY>
        <!ATTLIST dex
                min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #REQUIRED
                dm (1|2) #REQUIRED
                >
        <!ELEMENT end EMPTY>
        <!ATTLIST end
                min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #REQUIRED
                dm (1|2) #REQUIRED
                >
        <!ELEMENT int EMPTY>
        <!ATTLIST int
                min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #REQUIRED
                dm (1|2) #REQUIRED
                >
        <!ELEMENT edu EMPTY>
        <!ATTLIST edu
                min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #REQUIRED
                dm (1|2) #REQUIRED
                >
        <!ELEMENT soc EMPTY>
        <!ATTLIST soc
                min (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15) #REQUIRED
                dm (1|2) #REQUIRED
                >

=== JochenLinnemann/netShore-TCG/src/de/netshore/tcg/book1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE services SYSTEM "services.dtd">
<!--
   Copyright 2005, 2017 Jochen Linnemann

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<services>
    <service name="Navy" draft="1">
        <enlistment min="8">
            <int min="8" dm="1"/>
            <edu min="9" dm="2"/>
        </enlistment>
        <survival min="5">
            <int min="7" dm="2"/>
        </survival>
        <commission min="10">
            <soc min="9" dm="1"/>
        </commission>
        <promotion min="8">
            <edu min="8" dm="1"/>
        </promotion>
        <reenlistment min="6"/>
        <ranks without="Navy Starman" prefix="Navy">
            <r1 name="Ensign"/>
            <r2 name="Lieutenant"/>
            <r3 name="Lieutenant Commander"/>
            <r4 name="Commander"/>
            <r5 name="Captain"/>
            <r6 name="Admiral"/>
        </ranks>
        <mustering-out>
            <benefits>
                <b1 name="Low Passage"/>
                <b2 name="Int+1"/>
                <b3 name="Edu+2"/>
                <b4 name="Blade"/>
                <b5 name="Travellers' Aid"/>
                <b6 name="High Passage"/>
                <b7 name="Soc+2"/>
            </benefits>
            <cash>
                <c1 name="1000"/>
                <c2 name="5000"/>
                <c3 name="5000"/>
                <c4 name="10000"/>
                <c5 name="20000"/>
                <c6 name="50000"/>
                <c7 name="50000"/>
            </cash>
        </mustering-out>
        <skills eligibility="1">
            <automatic-skills>
                <r5 name="Soc+1"/>
                <r6 name="Soc+1"/>
            </automatic-skills>
            <personal-development>
                <s1 name="Str+1"/>
                <s2 name="Dex+1"/>
                <s3 name="End+1"/>
                <s4 name="Int+1"/>
                <s5 name="Edu+1"/>
                <s6 name="Soc+1"/>
            </personal-development>
            <service-skills>
                <s1 name="Ship's Boat"/>
                <s2 name="Vacc Suit"/>
                <s3 name="Forward Observer"/>
                <s4 name="Gunnery"/>
                <s5 name="Blade Combat"/>
                <s6 name="Gun Combat"/>
            </service-skills>
            <advanced-education>
                <s1 name="Vacc Suit"/>
                <s2 name="Mechanical"/>
                <s3 name="Electronics"/>
                <s4 name="Engineering"/>
                <s5 name="Gunnery"/>
                <s6 name="Jack of All Trades"/>
            </advanced-education>
            <advanced-education-edu8plus>
                <s1 name="Medical"/>
                <s2 name="Navigation"/>
                <s3 name="Egineering"/>
                <s4 name="Computer"/>
                <s5 name="Pilot"/>
                <s6 name="Administration"/>
            </advanced-education-edu8plus>
        </skills>
    </service>
    <service name="Marines" draft="2">
        <enlistment min="9">
            <int min="8" dm="1"/>
            <str min="8" dm="2"/>
        </enlistment>
        <survival min="6">
            <end min="8" dm="2"/>
        </survival>
        <commission min="9">
            <edu min="7" dm="1"/>
        </commission>
        <promotion min="9">
            <soc min="8" dm="1"/>
        </promotion>
        <reenlistment min="6"/>
        <ranks without="Marine" prefix="Marine">
            <r1 name="Lieutenant"/>
            <r2 name="Captain"/>
            <r3 name="Force Commander"/>
            <r4 name="Lieutenant Colonel"/>
            <r5 name="Colonel"/>
            <r6 name="Brigadier"/>
        </ranks>
        <mustering-out>
            <benefits>
                <b1 name="Low Passage"/>
                <b2 name="Int+2"/>
                <b3 name="Edu+1"/>
                <b4 name="Blade"/>
                <b5 name="Travellers' Aid"/>
                <b6 name="High Passage"/>
                <b7 name="Soc+2"/>
            </benefits>
            <cash>
                <c1 name="2000"/>
                <c2 name="5000"/>
                <c3 name="5000"/>
                <c4 name="10000"/>
                <c5 name="20000"/>
                <c6 name="30000"/>
                <c7 name="40000"/>
            </cash>
        </mustering-out>
        <skills eligibility="1">
            <automatic-skills>
                <r0 name="Cutlass"/>
                <r1 name="Revolver"/>
            </automatic-skills>
            <personal-development>
                <s1 name="Str+1"/>
                <s2 name="Dex+1"/>
                <s3 name="End+1"/>
                <s4 name="Gambling"/>
                <s5 name="Brawling"/>
                <s6 name="Blade Combat"/>
            </personal-development>
            <service-skills>
                <s1 name="Vehicle"/>
                <s2 name="Vacc Suit"/>
                <s3 name="Blade Combat"/>
                <s4 name="Gun Combat"/>
                <s5 name="Blade Combat"/>
                <s6 name="Gun Combat"/>
            </service-skills>
            <advanced-education>
                <s1 name="Vehicle"/>
                <s2 name="Mechanical"/>
                <s3 name="Electronics"/>
                <s4 name="Tactics"/>
                <s5 name="Blade Combat"/>
                <s6 name="Gun Combat"/>
            </advanced-education>
            <advanced-education-edu8plus>
                <s1 name="Medical"/>
                <s2 name="Tactics"/>
                <s3 name="Tactics"/>
                <s4 name="Computer"/>
                <s5 name="Leader"/>
                <s6 name="Administration"/>
            </advanced-education-edu8plus>
        </skills>
    </service>
    <service name="Army" draft="3">
        <enlistment min="5">
            <dex min="6" dm="1"/>
            <end min="5" dm="2"/>
        </enlistment>
        <survival min="5">
            <edu min="6" dm="2"/>
        </survival>
        <commission min="5">
            <end min="7" dm="1"/>
        </commission>
        <promotion min="6">
            <edu min="7" dm="1"/>
        </promotion>
        <reenlistment min="7"/>
        <ranks without="Army Trooper" prefix="Army">
            <r1 name="Lieutenant"/>
            <r2 name="Captain"/>
            <r3 name="Major"/>
            <r4 name="Lieutenant Colonel"/>
            <r5 name="Colonel"/>
            <r6 name="General"/>
        </ranks>
        <mustering-out>
            <benefits>
                <b1 name="Low Passage"/>
                <b2 name="Int+1"/>
                <b3 name="Edu+2"/>
                <b4 name="Gun"/>
                <b5 name="High Passage"/>
                <b6 name="Middle Passage"/>
                <b7 name="Soc+1"/>
            </benefits>
            <cash>
                <c1 name="2000"/>
                <c2 name="5000"/>
                <c3 name="10000"/>
                <c4 name="10000"/>
                <c5 name="10000"/>
                <c6 name="20000"/>
                <c7 name="30000"/>
            </cash>
        </mustering-out>
        <skills eligibility="1">
            <automatic-skills>
                <r0 name="Rifle"/>
                <r1 name="SMG"/>
            </automatic-skills>
            <personal-development>
                <s1 name="Str+1"/>
                <s2 name="Dex+1"/>
                <s3 name="End+1"/>
                <s4 name="Gambling"/>
                <s5 name="Edu+1"/>
                <s6 name="Brawling"/>
            </personal-development>
            <service-skills>
                <s1 name="Vehicle"/>
                <s2 name="Air/Raft"/>
                <s3 name="Gun Combat"/>
                <s4 name="Forward Observer"/>
                <s5 name="Blade Combat"/>
                <s6 name="Gun Combat"/>
            </service-skills>
            <advanced-education>
                <s1 name="Vehicle"/>
                <s2 name="Mechanical"/>
                <s3 name="Electronics"/>
                <s4 name="Tactics"/>
                <s5 name="Blade Combat"/>
                <s6 name="Gun Combat"/>
            </advanced-education>
            <advanced-education-edu8plus>
                <s1 name="Medical"/>
                <s2 name="Tactics"/>
                <s3 name="Tactics"/>
                <s4 name="Computer"/>
                <s5 name="Leader"/>
                <s6 name="Administration"/>
            </advanced-education-edu8plus>
        </skills>
    </service>
    <service name="Scouts" draft="4">
        <enlistment min="7">
            <int min="6" dm="1"/>
            <str min="8" dm="2"/>
        </enlistment>
        <survival min="7">
            <end min="9" dm="2"/>
        </survival>
        <commission/>
        <promotion/>
        <reenlistment min="3"/>
        <ranks without="Scout" prefix="Scout"/>
        <mustering-out>
            <benefits>
                <b1 name="Low Passage"/>
                <b2 name="Int+2"/>
                <b3 name="Edu+2"/>
                <b4 name="Blade"/>
                <b5 name="Gun"/>
                <b6 name="Scout Ship"/>
            </benefits>
            <cash>
                <c1 name="20000"/>
                <c2 name="20000"/>
                <c3 name="30000"/>
                <c4 name="30000"/>
                <c5 name="50000"/>
                <c6 name="50000"/>
                <c7 name="50000"/>
            </cash>
        </mustering-out>
